
server:
  port: 9001

spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.100:32065
        namespace: 52a41dfb-c913-4eca-ad0c-12cc0fa4d777
    sentinel:
      transport:
        dashboard: 192.168.100.100:32329
  zipkin:
    base-url: http://192.168.100.100:32239
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1

sms:
  qcloud:
    appId: 123423
    appKey: 52a41dfb-c913-4eca-ad0c-12cc0fa4d777
    sign: 52a4222-sdfs-2222-34333-33333333333