
server:
  port: 8005

spring:
  profiles: dev
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.100.100:32545/p2p_transaction_0?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: wanxinp2p
        druid:
          initial-size: 10
          min-idle: 10
          max-active: 50
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          filters: stat,wall
          max-pool-prepared-statement-per-connection-size: 20
          use-global-data-source-stat: true
          connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.100.100:32545/p2p_transaction_1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: wanxinp2p
        druid:
          initial-size: 10
          min-idle: 10
          max-active: 50
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          filters: stat,wall
          max-pool-prepared-statement-per-connection-size: 20
          use-global-data-source-stat: true
          connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    props:
      sql:
        show: true
    sharding:
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: ds${id % 2}
      binding-tables: claim,project,tender
      tables:
        claim:
          actual-data-nodes: ds${0..1}.claim_${0..1}
          database-strategy:
            inline:
              sharding-column: CONSUMER_ID
              algorithm-expression: ds${CONSUMER_ID % 2}  #发表人id%2
          table-strategy:
            inline:
              sharding-column: ID
              algorithm-expression: claim${ID % 2}  #id%2
        project:
          actual-data-nodes: ds${0..1}.project_${0..1}
          database-strategy:
            inline:
              sharding-column: CONSUMER_ID
              algorithm-expression: ds${CONSUMER_ID % 2}  #发表人id%2
          table-strategy:
            inline:
              sharding-column: ID
              algorithm-expression: project_${ID % 2}  #id%2
        tender:
          actual-data-nodes: ds${0..1}.tender_${0..1}
          database-strategy:
            inline:
              sharding-column: CONSUMER_ID
              algorithm-expression: ds${CONSUMER_ID % 2}  #发表人id%2
          table-strategy:
            inline:
              sharding-column: ID
              algorithm-expression: tender_${ID % 2}  #id%2
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.100:32065
        namespace: 52a41dfb-c913-4eca-ad0c-12cc0fa4d777
    sentinel:
      transport:
        dashboard: 192.168.100.100:32329
    stream:
      rocketmq:
        binder:
          name-server: 192.168.100.100:8876

      bindings:
        ouput:
          group: PID_START_REPAYMENT
          content-type: application/json
          destination: TP_START_REPAYMENT
  zipkin:
    base-url: http://192.168.100.100:32239
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  mapper-locations: classpath:xml/*.xml
  global-config:
    db-config:
      id-type: auto

swagger:
  enable: true